package com.william.treino;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.text.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
 String[] days,focuses; String[][] names,reps,exerciseIds; int[][] counts; JSONObject activePlan; boolean syncing=false;
 ExerciseCatalog catalog; final Random random=new Random();
 SharedPreferences prefs; JSONObject draft; LinearLayout root, body; int selected; TextView timerLabel; long deadline=0; Handler handler=new Handler(); int green=Color.rgb(113,229,172), muted=Color.rgb(163,178,190);
 final Runnable tick=new Runnable(){public void run(){long remain=Math.max(0,(deadline-SystemClock.elapsedRealtime()+999)/1000); if(timerLabel!=null){String label=remain>0?"Descanso  "+remain/60+":"+String.format(Locale.US,"%02d",remain%60):"Descanso concluído";if(!label.contentEquals(timerLabel.getText()))timerLabel.setText(label);} if(remain>0)handler.postDelayed(this,250); else if(deadline>0){deadline=0; android.media.ToneGenerator tone=new android.media.ToneGenerator(android.media.AudioManager.STREAM_NOTIFICATION,65);tone.startTone(android.media.ToneGenerator.TONE_PROP_ACK,300);handler.postDelayed(()->tone.release(),500);}}};
 @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("training",MODE_PRIVATE);loadCatalog();loadPlan();selected=prefs.getInt("day",Math.min(4,Math.max(0,Calendar.getInstance().get(Calendar.DAY_OF_WEEK)-2)));selected=Math.min(selected,days.length-1);if(b!=null)deadline=b.getLong("deadline",0);load();show();syncPlan(false);}
 @Override public void onSaveInstanceState(Bundle out){out.putLong("deadline",deadline);super.onSaveInstanceState(out);}
 void load(){try{draft=new JSONObject(prefs.getString("draft"+selected,"{}"));}catch(Exception e){draft=new JSONObject();}}
 void put(String k,Object v){try{draft.put(k,v);prefs.edit().putString("draft"+selected,draft.toString()).apply();}catch(Exception e){toast("Não foi possível salvar a série.");}}
 int dp(int x){return (int)(x*getResources().getDisplayMetrics().density);}
 TextView text(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setPadding(0,dp(6),0,dp(6));return t;}
 Button button(String label,Runnable action){Button b=new Button(this);b.setText(label);b.setAllCaps(false);b.setOnClickListener(v->action.run());return b;}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(10),dp(14),dp(12));GradientDrawable bg=new GradientDrawable();bg.setColor(Color.rgb(27,40,51));bg.setCornerRadius(dp(16));c.setBackground(bg);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=dp(12);body.addView(c,lp);return c;}
 void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(12),dp(16),dp(8));root.setBackgroundColor(Color.rgb(16,24,32)); root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(dp(16),dp(12)+i.getSystemWindowInsetTop(),dp(16),dp(8)+i.getSystemWindowInsetBottom());return i;});setContentView(root);TextView h=text(title,28,Color.WHITE);h.setTypeface(null,Typeface.BOLD);root.addView(h);ScrollView scroll=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));}
 void show(){prefs.edit().putInt("day",selected).apply();base("SetHarbor");body.addView(text(activePlan.optString("title","Meu treino"),14,muted));Spinner selector=new Spinner(this);selector.setContentDescription("Dia do treino");selector.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,days));selector.setSelection(selected);body.addView(selector);selector.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> p){} public void onItemSelected(android.widget.AdapterView<?> p,View v,int position,long id){if(position!=selected){selected=position;load();show();}}});body.addView(text(focuses[selected],18,green));
 Spinner phase=new Spinner(this);phase.setContentDescription("Modo do treino");phase.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Semana 1 · 2 séries · RIR 3–4","Semana 2 · volume completo · RIR 2","Normal · volume completo · RIR 1–2"}));phase.setSelection(prefs.getInt("phase",0));body.addView(phase);phase.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){if(pos!=prefs.getInt("phase",0)){prefs.edit().putInt("phase",pos).apply();show();}}});
 LinearLayout timer=card();timerLabel=text("Descanso",18,green);timer.addView(timerLabel);LinearLayout durations=new LinearLayout(this);for(int sec:new int[]{60,90,120})durations.addView(button(sec+" s",()->{deadline=SystemClock.elapsedRealtime()+sec*1000;handler.removeCallbacks(tick);tick.run();}),new LinearLayout.LayoutParams(0,-2,1));timer.addView(durations);timer.addView(button("Parar",()->{deadline=0;handler.removeCallbacks(tick);timerLabel.setText("Descanso");}));if(deadline>0){handler.removeCallbacks(tick);tick.run();}
 for(int e=0;e<names[selected].length;e++)addExercise(e);

 body.addView(text("Progrida quando atingir o topo da faixa em todas as séries. Confira a unidade de carga nos detalhes. Em exercícios assistidos, reduza a assistência para progredir; peso corporal usa 0 kg sem carga adicional. Aquecimentos não entram nas séries.",13,muted));body.addView(button("Concluir e salvar treino",()->finishWorkout()));body.addView(button("Histórico de treinos",()->history()));body.addView(button("Importar ficha de treino",()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,44);}));body.addView(button("Atualização online",()->configureSync()));body.addView(button("Exportar backup",()->{Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"meu-treino-backup.json");startActivityForResult(i,42);}));body.addView(button("Restaurar backup",()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,43);}));}
 ImageButton exerciseIcon(int drawable,String description,Runnable action){
  ImageButton icon=new ImageButton(this);icon.setImageResource(drawable);icon.setScaleType(ImageView.ScaleType.CENTER);icon.setContentDescription(description);icon.setTooltipText(description.split(" · ")[0]);
  android.util.TypedValue ripple=new android.util.TypedValue();getTheme().resolveAttribute(android.R.attr.selectableItemBackgroundBorderless,ripple,true);icon.setBackgroundResource(ripple.resourceId);icon.setOnClickListener(v->action.run());return icon;
 }
 void addExercise(int exercise){
  LinearLayout c=card();JSONObject actual=effectiveExercise(exercise);String displayed=actual.optString("name");
  LinearLayout header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);header.addView(text(displayed,19,Color.WHITE),new LinearLayout.LayoutParams(0,-2,1));c.addView(header);
  JSONObject known=catalog.resolve(actual);
  if(known!=null){
   LinearLayout details=new LinearLayout(this);details.setOrientation(LinearLayout.VERTICAL);details.setVisibility(View.GONE);
   details.addView(text("Grupo: "+catalog.labels("groups",new JSONArray().put(known.optString("group"))),13,muted));
   details.addView(text("Principais: "+catalog.labels("muscles",known.optJSONArray("primaryMuscles")),13,muted));
   String secondary=catalog.labels("muscles",known.optJSONArray("secondaryMuscles"));if(!secondary.isEmpty())details.addView(text("Secundários: "+secondary,13,muted));
   String stabilizers=catalog.labels("muscles",known.optJSONArray("stabilizerMuscles"));if(!stabilizers.isEmpty())details.addView(text("Estabilizadores: "+stabilizers,13,muted));
   details.addView(text("Equipamento: "+catalog.labels("equipment",known.optJSONArray("equipment"))+" · "+catalog.loadHint(known),13,muted));
   details.addView(text(known.optString("notes"),13,muted));
   String slot=exerciseIds[selected][exercise];ImageButton info=exerciseIcon(R.drawable.ic_exercise_info,"Mostrar detalhes · "+slot,()->{});
   info.setOnClickListener(v->{boolean expanded=details.getVisibility()!=View.VISIBLE;details.setVisibility(expanded?View.VISIBLE:View.GONE);info.setContentDescription((expanded?"Ocultar detalhes · ":"Mostrar detalhes · ")+slot);});
   header.addView(info,new LinearLayout.LayoutParams(dp(48),dp(48)));
   header.addView(exerciseIcon(R.drawable.ic_exercise_swap,"Trocar por similar · "+slot,()->switchExercise(exercise)),new LinearLayout.LayoutParams(dp(48),dp(48)));c.addView(details);
   if(draft.optJSONObject(ExerciseSession.OVERRIDES)!=null&&draft.optJSONObject(ExerciseSession.OVERRIDES).has(slot)){c.addView(text("Só neste treino",13,green));details.addView(text("Planejado: "+names[selected][exercise],13,muted));}
  }
  int n=prefs.getInt("phase",0)==0?Math.min(2,counts[selected][exercise]):counts[selected][exercise];
  c.addView(text(n+" séries × "+reps[selected][exercise]+" reps",14,green));
  String last=lastPerformance(exercise);if(!last.isEmpty())c.addView(text("Último: "+last,13,muted));
  TextView heading=text("Série     Carga (kg)        Repetições       Feita",12,muted);c.addView(heading);
  ArrayList<LinearLayout> rows=new ArrayList<>();ArrayList<CheckBox> checks=new ArrayList<>();
  boolean[] expanded={false};TextView progress=text("",13,green);Button toggle=button("Mostrar séries concluídas",()->{});
  Runnable refresh=()->{int completed=0;for(int i=0;i<rows.size();i++){boolean done=checks.get(i).isChecked();if(done)completed++;rows.get(i).setVisibility(done&&!expanded[0]?View.GONE:View.VISIBLE);}progress.setText(completed+" de "+n+" séries concluídas");progress.setVisibility(completed>0?View.VISIBLE:View.GONE);toggle.setVisibility(completed>0?View.VISIBLE:View.GONE);toggle.setText(expanded[0]?"Ocultar séries concluídas":"Mostrar séries concluídas");heading.setVisibility(completed==n&&!expanded[0]?View.GONE:View.VISIBLE);};
  for(int index=0;index<n;index++){
   String key=exercise+"_"+index;LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);
   row.addView(text(""+(index+1),16,muted),new LinearLayout.LayoutParams(dp(28),-2));
   EditText kg=field(draft.optString(key+"kg",""),true,v->put(key+"kg",v));EditText rp=field(draft.optString(key+"reps",""),false,v->put(key+"reps",v));
   kg.setContentDescription("Carga · "+exerciseIds[selected][exercise]+" · "+(index+1));rp.setContentDescription("Repetições · "+exerciseIds[selected][exercise]+" · "+(index+1));row.addView(kg,new LinearLayout.LayoutParams(0,dp(54),1));row.addView(rp,new LinearLayout.LayoutParams(0,dp(54),1));
   CheckBox done=new CheckBox(this);done.setChecked(draft.optBoolean(key+"done",false));done.setContentDescription("Série "+(index+1)+" concluída em "+displayed);
   rows.add(row);checks.add(done);done.setOnCheckedChangeListener((b,checked)->{put(key+"done",checked);if(checked){row.clearFocus();android.view.inputmethod.InputMethodManager keyboard=(android.view.inputmethod.InputMethodManager)getSystemService(INPUT_METHOD_SERVICE);if(keyboard!=null)keyboard.hideSoftInputFromWindow(row.getWindowToken(),0);}refresh.run();});row.addView(done);c.addView(row);
  }
  c.addView(progress);c.addView(toggle);toggle.setOnClickListener(v->{expanded[0]=!expanded[0];refresh.run();});refresh.run();
 }
 interface Change{void accept(String s);}
 EditText field(String initial,boolean decimal,Change change){EditText f=new EditText(this);f.setSingleLine();f.setTextColor(Color.WHITE);f.setTextSize(16);f.setHint(decimal?"kg":"reps");f.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|(decimal?android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL:0));f.setText(initial);f.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){change.accept(s.toString());}public void afterTextChanged(Editable e){}});return f;}
 JSONArray records(){try{return new JSONArray(prefs.getString("history","[]"));}catch(Exception e){return new JSONArray();}}
 String lastPerformance(int exercise){JSONArray a=records();for(int i=a.length()-1;i>=0;i--){JSONObject rec=a.optJSONObject(i);if(rec==null)continue;JSONObject oldPlan=rec.optJSONObject("plan");if(oldPlan==null)continue;JSONArray oldDays=oldPlan.optJSONArray("days");JSONObject vals=rec.optJSONObject("sets");int day=rec.optInt("day",-1);if(vals==null||oldDays==null||day<0||day>=oldDays.length())continue;JSONArray exercises=oldDays.optJSONObject(day).optJSONArray("exercises");for(int e=0;e<exercises.length();e++){JSONObject item=exercises.optJSONObject(e);if(!ExerciseSession.sameExercise(effectiveExercise(exercise),item,catalog))continue;ArrayList<String> parts=new ArrayList<>();for(int k=0;k<item.optInt("sets",0);k++){String key=e+"_"+k;if(vals.optBoolean(key+"done"))parts.add(vals.optString(key+"kg")+" kg × "+vals.optString(key+"reps"));}if(!parts.isEmpty())return String.join(" / ",parts);}}return "";}

 void finishWorkout(){int done=0;for(int e=0;e<names[selected].length;e++)for(int s=0;s<(prefs.getInt("phase",0)==0?Math.min(2,counts[selected][e]):counts[selected][e]);s++){String k=e+"_"+s;if(draft.optBoolean(k+"done")){try{double weight=Double.parseDouble(draft.optString(k+"kg").replace(',','.'));int reps=Integer.parseInt(draft.optString(k+"reps"));if(weight<0||!Double.isFinite(weight)||reps<=0)throw new Exception();}catch(Exception err){toast("Preencha carga e repetições válidas nas séries marcadas. Use 0 kg para peso corporal.");return;}done++;}}if(done==0){toast("Marque ao menos uma série feita para salvar.");return;}new AlertDialog.Builder(this).setTitle("Salvar treino?").setMessage(done+" séries concluídas. As séries não marcadas ficam fora do histórico.").setNegativeButton("Voltar",null).setPositiveButton("Salvar",(d,w)->{try{JSONObject sets=new JSONObject();int n=prefs.getInt("phase",0);for(int e=0;e<names[selected].length;e++)for(int s=0;s<(n==0?Math.min(2,counts[selected][e]):counts[selected][e]);s++){String k=e+"_"+s;if(draft.optBoolean(k+"done")){sets.put(k+"done",true);sets.put(k+"kg",draft.optString(k+"kg"));sets.put(k+"reps",draft.optString(k+"reps"));}}JSONArray a=records();JSONObject rec=new JSONObject();rec.put("date",new SimpleDateFormat("dd/MM/yyyy HH:mm",Locale.getDefault()).format(new Date()));rec.put("day",selected);rec.put("phase",n);rec.put("sets",sets);rec.put("plan",ExerciseSession.snapshot(activePlan,selected,draft,catalog));a.put(rec);boolean ok=prefs.edit().putString("history",a.toString()).remove("draft"+selected).commit();if(!ok){toast("Falha ao gravar. Seu treino continua aberto.");return;}load();show();toast("Treino salvo!");}catch(Exception err){toast("Erro ao salvar. Seu treino continua aberto.");}}).show();}
 void history(){base("Histórico");JSONArray a=records();if(a.length()==0)body.addView(text("Nenhum treino concluído ainda.",18,muted));for(int i=a.length()-1;i>=0;i--){JSONObject rec=a.optJSONObject(i);if(rec==null)continue;JSONObject plan=rec.optJSONObject("plan");if(plan==null)continue;JSONObject day=plan.optJSONArray("days").optJSONObject(rec.optInt("day"));LinearLayout c=card();c.addView(text(day.optString("name")+" · "+rec.optString("date"),18,green));JSONObject vals=rec.optJSONObject("sets");JSONArray exercises=day.optJSONArray("exercises");if(vals==null)continue;for(int e=0;e<exercises.length();e++){JSONObject item=exercises.optJSONObject(e);ArrayList<String> entries=new ArrayList<>();for(int k=0;k<item.optInt("sets");k++){String key=e+"_"+k;if(vals.optBoolean(key+"done"))entries.add(vals.optString(key+"kg")+" kg × "+vals.optString(key+"reps"));}if(!entries.isEmpty())c.addView(text(item.optString("name")+"\n"+String.join(" / ",entries),14,Color.WHITE));}}body.addView(button("Voltar ao treino",()->show()));}
 @Override public void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(req==44&&result==RESULT_OK&&data!=null){try(java.io.InputStream stream=getContentResolver().openInputStream(data.getData())){JSONObject plan=new JSONObject(readLimited(stream));WorkoutPlan.validate(plan);new AlertDialog.Builder(this).setTitle("Importar ficha?").setMessage(plan.getString("title")+" • "+plan.getJSONArray("days").length()+" dias. Seu histórico será preservado.").setNegativeButton("Cancelar",null).setPositiveButton("Importar",(dialog,which)->applyPlan(plan,true)).show();}catch(Exception err){toast("Ficha inválida: "+err.getMessage());}}if(req==43&&result==RESULT_OK&&data!=null){try(java.io.InputStream stream=getContentResolver().openInputStream(data.getData())){java.io.ByteArrayOutputStream bytes=new java.io.ByteArrayOutputStream();byte[] buf=new byte[8192];int size;while((size=stream.read(buf))!=-1){bytes.write(buf,0,size);if(bytes.size()>10*1024*1024)throw new Exception("Arquivo muito grande");}JSONObject restored=new JSONObject(bytes.toString("UTF-8"));validateBackup(restored);new AlertDialog.Builder(this).setTitle("Restaurar backup?").setMessage("Isso substituirá o histórico e as séries em andamento por este backup.").setNegativeButton("Cancelar",null).setPositiveButton("Restaurar",(dialog,which)->{try{SharedPreferences.Editor editor=prefs.edit().putString("history",restored.getJSONArray("history").toString()).putInt("phase",restored.getInt("phase"));if(restored.has("plan"))editor.putString("plan",restored.getJSONObject("plan").toString());else editor.remove("plan");for(int d=0;d<7;d++)editor.remove("draft"+d);for(int d=0;d<(restored.has("plan")?restored.getJSONObject("plan").getJSONArray("days").length():5);d++)editor.putString("draft"+d,restored.getJSONObject("draft"+d).toString());if(!editor.commit())throw new Exception();loadPlan();selected=Math.min(selected,days.length-1);load();show();toast("Backup restaurado.");}catch(Exception err){toast("Não foi possível restaurar.");}}).show();}catch(Exception err){toast("Backup inválido ou incompatível.");}}if(req==42&&result==RESULT_OK&&data!=null){try(java.io.OutputStream stream=getContentResolver().openOutputStream(data.getData())){JSONObject backup=new JSONObject();backup.put("version",3);backup.put("plan",activePlan);backup.put("history",records());backup.put("phase",prefs.getInt("phase",0));for(int d=0;d<days.length;d++)backup.put("draft"+d,new JSONObject(prefs.getString("draft"+d,"{}")));stream.write(backup.toString(2).getBytes(java.nio.charset.StandardCharsets.UTF_8));toast("Backup exportado.");}catch(Exception err){toast("Não foi possível exportar.");}}}
 void validateBackup(JSONObject backup) throws Exception {int version=backup.getInt("version");if(version!=1&&version!=2&&version!=3)throw new Exception();int dayCount=5;if(version>=2){WorkoutPlan.validate(backup.getJSONObject("plan"));dayCount=backup.getJSONObject("plan").getJSONArray("days").length();}int phase=backup.getInt("phase");if(phase<0||phase>2)throw new Exception();JSONArray history=backup.getJSONArray("history");for(int i=0;i<history.length();i++){JSONObject rec=history.getJSONObject(i);JSONObject old=rec.optJSONObject("plan");if(old!=null)WorkoutPlan.validate(old);int day=rec.getInt("day");if(day<0||day>=(old!=null?old.getJSONArray("days").length():5))throw new Exception();rec.getString("date");rec.getJSONObject("sets");}JSONObject restoredPlan=version>=2?backup.getJSONObject("plan"):originalPlan();for(int d=0;d<dayCount;d++)ExerciseSession.validateOverrides(restoredPlan,d,backup.getJSONObject("draft"+d),catalog);}
 String readLimited(java.io.InputStream stream) throws Exception {java.io.ByteArrayOutputStream bytes=new java.io.ByteArrayOutputStream();byte[] buffer=new byte[8192];int n;while((n=stream.read(buffer))!=-1){bytes.write(buffer,0,n);if(bytes.size()>1024*1024)throw new Exception("Arquivo maior que 1 MB");}return bytes.toString("UTF-8");}
 JSONObject originalPlan() throws Exception {try(java.io.InputStream input=getAssets().open("default-plan.json")){return new JSONObject(readLimited(input));}}
 void loadCatalog(){try(java.io.InputStream input=getAssets().open("exercise-catalog.json")){catalog=new ExerciseCatalog(new JSONObject(readLimited(input)));catalog.bindLegacyPlan(originalPlan());}catch(Exception err){throw new IllegalStateException("Falha ao carregar catálogo",err);}}
 JSONObject effectiveExercise(int exercise){try{return ExerciseSession.effective(ExerciseSession.planned(activePlan,selected,exercise),draft,catalog);}catch(Exception err){throw new IllegalStateException("Troca inválida",err);}}
 void switchExercise(int exercise){try{
  if(ExerciseSession.hasData(draft,exercise,counts[selected][exercise])){toast("Apague os dados deste exercício antes de trocar.");return;}
  List<JSONObject> alternatives=catalog.alternatives(catalog.resolve(effectiveExercise(exercise)));
  if(alternatives.isEmpty()){toast("Nenhuma alternativa similar disponível.");return;}
  JSONObject changed=new JSONObject(draft.toString());ExerciseSession.switchTo(activePlan,selected,exercise,changed,catalog,alternatives.get(random.nextInt(alternatives.size())).getString("id"));
  if(!prefs.edit().putString("draft"+selected,changed.toString()).commit())throw new Exception("Falha ao gravar");
  int y=((ScrollView)body.getParent()).getScrollY();draft=changed;show();((ScrollView)body.getParent()).post(()->((ScrollView)body.getParent()).scrollTo(0,y));
 }catch(Exception err){toast("Não foi possível trocar: "+err.getMessage());}}
 void loadPlan(){try{JSONObject original;try(java.io.InputStream input=getAssets().open("default-plan.json")){original=new JSONObject(readLimited(input));}activePlan=new JSONObject(prefs.getString("plan",original.toString()));WorkoutPlan.validate(activePlan);JSONArray saved=records();boolean changed=false;for(int i=0;i<saved.length();i++){JSONObject rec=saved.getJSONObject(i);if(!rec.has("plan")){rec.put("plan",original);changed=true;}}if(changed)prefs.edit().putString("history",saved.toString()).commit();JSONArray items=activePlan.getJSONArray("days");days=new String[items.length()];focuses=new String[items.length()];names=new String[items.length()][];reps=new String[items.length()][];counts=new int[items.length()][];exerciseIds=new String[items.length()][];for(int d=0;d<items.length();d++){JSONObject day=items.getJSONObject(d);days[d]=day.getString("name");focuses[d]=day.optString("focus");JSONArray ex=day.getJSONArray("exercises");names[d]=new String[ex.length()];reps[d]=new String[ex.length()];counts[d]=new int[ex.length()];exerciseIds[d]=new String[ex.length()];for(int e=0;e<ex.length();e++){JSONObject item=ex.getJSONObject(e);names[d][e]=item.getString("name");reps[d][e]=item.getString("reps");counts[d][e]=item.getInt("sets");exerciseIds[d][e]=item.getString("id");}}}catch(Exception err){throw new IllegalStateException("Falha ao carregar ficha",err);}}
 boolean hasDrafts(){for(int d=0;d<days.length;d++){try{if(new JSONObject(prefs.getString("draft"+d,"{}")).length()>0)return true;}catch(Exception err){return true;}}return false;}
 void applyPlan(JSONObject plan,boolean feedback){try{WorkoutPlan.validate(plan);if(hasDrafts()){if(feedback)toast("Conclua os treinos em andamento antes de trocar a ficha. Seus registros foram mantidos.");return;}if(!prefs.edit().putString("plan",plan.toString()).commit())throw new Exception("Falha ao gravar");loadPlan();selected=Math.min(selected,days.length-1);load();show();if(feedback)toast("Ficha atualizada. Histórico preservado.");}catch(Exception err){if(feedback)toast("Não foi possível atualizar: "+err.getMessage());}}
 void configureSync(){EditText field=new EditText(this);field.setText(prefs.getString("planUrl",""));field.setHint("https://…/treino.json");field.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_URI);new AlertDialog.Builder(this).setTitle("Atualização automática ao abrir").setMessage("Configure uma URL HTTPS com a ficha JSON. O app verifica ao abrir e aplica revisões novas quando não houver treino em andamento. Sem URL, continua offline.").setView(field).setNegativeButton("Cancelar",null).setNeutralButton("Desativar",(d,w)->prefs.edit().remove("planUrl").apply()).setPositiveButton("Salvar e verificar",(d,w)->{String url=field.getText().toString().trim();try{java.net.URI uri=new java.net.URI(url);if(!"https".equalsIgnoreCase(uri.getScheme())||uri.getHost()==null||uri.getUserInfo()!=null)throw new Exception();prefs.edit().putString("planUrl",url).apply();syncPlan(true);}catch(Exception err){toast("Informe uma URL HTTPS válida.");}}).show();}
 void syncPlan(boolean feedback){String address=prefs.getString("planUrl","");if(address.isEmpty()||syncing)return;syncing=true;new Thread(()->{try{javax.net.ssl.HttpsURLConnection connection=(javax.net.ssl.HttpsURLConnection)new java.net.URL(address).openConnection();connection.setConnectTimeout(10000);connection.setReadTimeout(10000);connection.setInstanceFollowRedirects(false);JSONObject fetched;try{if(connection.getResponseCode()!=200)throw new Exception("Resposta HTTP inválida");try(java.io.InputStream input=connection.getInputStream()){fetched=new JSONObject(readLimited(input));}WorkoutPlan.validate(fetched);}finally{connection.disconnect();}handler.post(()->{syncing=false;if(isFinishing()||isDestroyed())return;if(fetched.optLong("revision")>activePlan.optLong("revision"))applyPlan(fetched,feedback);else if(feedback)toast("Sua ficha já está atualizada.");});}catch(Exception err){handler.post(()->{syncing=false;if(feedback&&!isFinishing()&&!isDestroyed())toast("Não foi possível buscar a ficha. O treino offline continua disponível.");});}}).start();}
 @Override public void onDestroy(){handler.removeCallbacks(tick);super.onDestroy();}
}
